# Generated by Django 5.1.5 on 2025-03-12 05:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewratig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewRatig',
            new_name='ReviewRating',
        ),
    ]
