# Generated by Django 5.1.5 on 2025-03-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_vriations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='vriations',
            new_name='variations',
        ),
    ]
