# Generated by Django 5.1.1 on 2024-12-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0003_orders_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='deliverd',
            new_name='delivered',
        ),
    ]
